# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

FROM quay.io/packit/packit-service-fedmsg:dev

RUN dnf -y install make findutils python3-pytest python3-flexmock && dnf -y clean all
